// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMr2X3RGXWTEHRmL0zq-PGLNKhXyCnpk',
    appId: '1:1092334211125:web:40e2aac56b65c20435617c',
    messagingSenderId: '1092334211125',
    projectId: 'onamfund',
    authDomain: 'onamfund.firebaseapp.com',
    storageBucket: 'onamfund.firebasestorage.app',
    measurementId: 'G-5FK29RDJZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwxa2Uhtjb8YDpe6iauCzlPnoZJY6huM',
    appId: '1:1092334211125:android:f2c017122f8878df35617c',
    messagingSenderId: '1092334211125',
    projectId: 'onamfund',
    storageBucket: 'onamfund.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlC4-CUnUpJxmCPizcZBdxNZL50gPKkAw',
    appId: '1:1092334211125:ios:d84b79bea941b7af35617c',
    messagingSenderId: '1092334211125',
    projectId: 'onamfund',
    storageBucket: 'onamfund.firebasestorage.app',
    iosBundleId: 'com.onam.fund.onam',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlC4-CUnUpJxmCPizcZBdxNZL50gPKkAw',
    appId: '1:1092334211125:ios:d84b79bea941b7af35617c',
    messagingSenderId: '1092334211125',
    projectId: 'onamfund',
    storageBucket: 'onamfund.firebasestorage.app',
    iosBundleId: 'com.onam.fund.onam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMr2X3RGXWTEHRmL0zq-PGLNKhXyCnpk',
    appId: '1:1092334211125:web:bf2c7e3f5449110435617c',
    messagingSenderId: '1092334211125',
    projectId: 'onamfund',
    authDomain: 'onamfund.firebaseapp.com',
    storageBucket: 'onamfund.firebasestorage.app',
    measurementId: 'G-RQDBNKJXBX',
  );
}
